### ISSUE TITLE
Cancel active tasks

### ISSUE THREAD

**Issue by mxgrey** [open-rmf/rmf_ros2#10]
## Feature request

Cancel tasks that are already being performed.

### Description

We should allow users to cancel tasks that have already been started.

Each `Phase` type already implements a `cancel` behavior, but there may be `Task` types whose state changes while completing phases, and that may complicate what it means to "cancel" the task. For example, what should be the behavior of canceling a Delivery Task after the robot has already picked up the item to deliver it? Should the robot return the item to its pickup location? Should the robot just finish the delivery? Should the robot bring it to some other discarding location?

### Implementation considerations

To achieve robust cancellation behavior, we should have a way for the `Task` instance to generate new cancellation phases based on the current phase of the task. There are many ways this could be implemented, but the API that I would recommend is to change [`Task::cancel()`](https://github.com/open-rmf/rmf_ros2/blob/9aeb7676d18b379bdc5f4c07907545c850814823/rmf_fleet_adapter/src/rmf_fleet_adapter/Task.hpp#L123) to return a `std::shared_ptr<Task>` which contains a new `Task` instance that describes the steps a robot must complete to safely cancel its current task. If no steps are needed, then this could simply return a nullptr. When the return value is not null, then the returned task becomes the new active task of the robot.

**Comment by Yadunund** [comment]
PR https://github.com/open-rmf/rmf_ros2/pull/168 adds support for cancelling tasks in any state.
