### ISSUE TITLE
finishing task wont get re-added after task reassignment

### ISSUE THREAD

**Issue by youliangtan** [open-rmf/rmf_ros2#138]
## Issue

I will use a rmf_demo world to illustrate this issue.

In the new `rmf demos` hotel world, there are 2 cleaning robots operating under a fleet adapter. `Park` task is chosen as the finishing task of the cleaner robots. The expectation here is, cleaning robots will head back to their respective parking spots after finishing their tasks.

run:
```
ros2 launch rmf_demos_gz hotel.launch.xml
```

Then, we will submit 2 cleaning tasks to the robot, when submit the first task
```bash
ros2 run rmf_demos_tasks dispatch_clean -cs clean_lobby --use_sim_time
ros2 run rmf_demos_tasks dispatch_clean -cs clean_waiting_area --use_sim_time
```

---

1. When submit first clean task, assignment:
```bash
 --Agent: 0
 --Agent: 1
     <Clean0: 43676000000.000000, 43725000000.000000, 134054395504.000000, 99.190534%>
     <ParkRobotf0627c: 134054395504.000000, 134054395504.000000, 179361137360.000000, 98.808748%>

#Tasks queue (active | pending)
Robot1: X | Clean0, ParkRobotf0627c
Robot2: X | X
```

Immediately, the first `Clean0` task tuns from pending to active.

2. Submit 2nd clean task.  Since only pending tasks can get reassigned, `Clean0` is not known to the task planner. In this scenario, `Clean1` task is allocated to a different robot. Here we will see that the previously added Park task is removed and not get re-added again.
```bash
assignments:
 --Agent: 0
     <Clean1: 67879000000.000000, 67942000000.000000, 198391058556.000000, 98.233099%>
     <ParkRobot44e59d: 198391058556.000000, 198391058556.000000, 289777678867.000000, 97.389582%>
 --Agent: 1

#Tasks queue (active | pending)
Robot1: Clean0 | 
Robot2: Clean1 | ParkRobot44e59d
```

Expected outcome: The task planner will append a `Park` task to agents that have (user submitted) task(s) in their task queues, regardless of active/pending :
```bash
# Tasks queue (active | pending)
Robot1: Clean0 | ParkRobot90834
Robot2: Clean1 | ParkRobot44e59d
```

**Comment by mxgrey** [comment]
I think instead of framing the parking behavior as a "finishing task" we should think of it in terms of "Idle Behavior". Right now there's only one "Idle Behavior" which is the Responsive Wait. We should allow users to set the Idle Behavior to something other than Responsive Wait, i.e. Park, Charge, or whatever else. That way we can be certain that whenever a robot is out of tasks it will automatically jump into its Idle Behavior, whatever that happens to be, regardless of any replanning that might have happened.
