### ISSUE TITLE
linking error when building rmf_fleet_adapter

### ISSUE THREAD

**Issue by mayman99** [open-rmf/rmf_ros2#148]
## Bug report

`
undefined reference to symbol 'pthread_rwlock_unlock@@GLIBC_2.2.5' make
` when building the package
### Required information:

- Operating system and version:
  - Ubuntu 20.04
- OpenRMF installation type:
  - source
- OpenRMF version or commit hash
  - latest, 66cd1dc
- ROS distribution and version:
  - 
- ROS installation type:
  - binary
- Package or library, if applicable:
  - rmf_fleet_adapter

### Description of the bug

fixed by adding `-pthread` to `experimental_lift_watchdog` target link libs
```
target_link_libraries(experimental_lift_watchdog
  PUBLIC
    -pthread
  PRIVATE
    ${rclcpp_LIBRARIES}
    ${rmf_fleet_msgs_LIBRARIES}
    ${std_msgs_LIBRARIES}
)
```

### Additional information

`rmf_fleet_adapter`

**Comment by mxgrey** [comment]
Linkers are awfully mysterious.. I have no idea how you're the first one to be dealt this error.

There's a preferable fix to this problem than explicitly linking `libpthread`:

```
find_package(Threads REQUIRED)
...
target_link_libraries(target_name [PUBLIC|PRIVATE] Threads::Threads)
```

That should fix the linking problem while also being cross-platform.

**Comment by Yadunund** [comment]
Potentially fixed by https://github.com/open-rmf/rmf_ros2/pull/204
