### ISSUE TITLE
segfault on task cancellation

### ISSUE THREAD

**Issue by cnboonhan** [open-rmf/rmf_ros2#175]
I seem to segfault the fleet adapter when i try to cancel tasks using swagger api of rmf-web.

https://user-images.githubusercontent.com/12628669/154209296-ec4e203c-993b-4b21-878e-af2b7d589957.mp4

To reproduce, use this workspace: [test.repos.txt](https://github.com/open-rmf/rmf_ros2/files/8077325/test.repos.txt) then  run

```
# RMF
ros2 launch rmf_demos_gz office.launch.xml server_uri:="ws://localhost:8001" headless:=1 use_sim_time:=false

# rmf-web
RMF_API_SERVER_USE_SIM_TIME=false rmf_api_server
npm run start:react
(in task panel in dashboard , Send Loop request)

# localhost:8000/docs, send this under POST /task/cancel_task
{
  "type": "cancel_task_request",
  "task_id": "patrol.dispatch-0",
  "labels": [
    "string"
  ]
}
```

**Comment by mxgrey** [comment]
This is fixed by https://github.com/open-rmf/rmf_task/pull/57
