### ISSUE TITLE
[Other issue]: Open-RMF and UAV

### ISSUE THREAD

**Issue by Cristian-wp** [open-rmf/rmf_ros2#305]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Hello, this framework has already been used to manage aerial drones fleet? Or maybe can be used?

**Comment by arjo129** [comment]
No not yet. I think aerial vehicles are out of scope.
