### ISSUE TITLE
[Other issue]: Custom RMF package development.

### ISSUE THREAD

**Issue by rocker12121** [open-rmf/rmf_ros2#399]
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

I want to make a custom rmf package that is very lightweight and only cares about traffic conflict detection and scheduling. Can i just use the rmf_traffic repository/package for that? What is the most appropriate way to do that?

**Comment by Yadunund** [comment]
Please ask questions like this on our discussions board https://github.com/open-rmf/rmf/discussions
