### ISSUE TITLE
Switch MirrorManager unregistering to use a heartbeat

### ISSUE THREAD

**Issue by gbiggs** [open-rmf/rmf_ros2#72]
### Description

Change the way `MirrorManager` objects unregister from the `Schedule` node from using an explicit unregister service to instead using a heartbeat to signal presence.

See [this comment](https://github.com/open-rmf/rmf_ros2/pull/61#discussion_r658586729) for details.

### Implementation considerations

DDS heartbeats seem reliable enough to support the proposed approach.

### Alternatives

Stick with the unregister service client, which requires managing a client and relies on the object destructor being called while the client is valid.

**Comment by mxgrey** [comment]
This is effectively fixed by #86 where queries will be periodically cleared out if they're not in use anymore.
